#include "psx_main.h"

#include "Base/i_main.h"
#include "cdmaptbl.h"
#include "FatalErrors.h"
#include "PsyDoom/Cheats.h"
#include "PsyDoom/Config/Config.h"
#include "PsyDoom/Controls.h"
#include "PsyDoom/Game.h"
#include "PsyDoom/Input.h"
#include "PsyDoom/IntroLogos.h"
#include "PsyDoom/ModMgr.h"
#include "PsyDoom/PlayerPrefs.h"
#include "PsyDoom/ProgArgs.h"
#include "PsyDoom/PsxVm.h"
#include "PsyDoom/Utils.h"
#include "PsyDoom/Video.h"

#if PSYDOOM_3DS
    #include "Platform_3DS.h"
#endif

#if PSYDOOM_MODS
    // PsyDoom: a flag set to 'true' if the result of demo playback is unexpected/wrong (when checking demo results).
    // This is used to set the exit code for the application accordingly ('1' if the demo result checks fail, '0' otherwise).
    bool gbCheckDemoResultFailed = false;
#endif

//------------------------------------------------------------------------------------------------------------------------------------------
// This was the old reverse engineered entrypoint for PSXDOOM.EXE, which executed before 'main()' was called.
//
// The code that was previously here was generated by the compiler and/or toolchain and did stuff which the user application could not do
// such as deciding on the value of the 'gp' register, zero initializing the BSS section global variables and so on. Basically all of the
// bootstrap stuff before the C program can run.
//
// There used to be other actual PSX code in here, but as layers of emulation were removed this function had less and less purpose.
// Now I'm using it as a place to initialize all of PsyDoom's systems before launching the original 'main()' of PSXDOOM.EXE.
//
// Code which was removed includes:
//  (1) Save and restore the current return address register (ra) for returning control to operating system after the program is done.
//  (2) Setting the value of the 'global pointer' (gp) register which is used as a base to reference many global variables.
//      For the 'Greatest Hits' edition of PlayStation Doom (US) 'gp' was set to: 0x800775E0
//  (3) Setting the value of the 'frame pointer' (fp) register.
//  (4) Setting the value of the 'stack pointer' (sp) register.
//  (5) Zero initializing the BSS section globals. These are globals with a defaulted (0) value.
//  (6) Calling 'LIBAPI_InitHeap' to initialize the PsyQ SDK Heap.
//      Note that since Doom used it's own zone memory management system, that call was effectively useless.
//      It never once asked for memory from the PsyQ SDK, nor did any of the PsyQ functions used.
//      Doom's own heap would have been corrupted if LIBAPI's heap was in conflicting use of the same memory.
//------------------------------------------------------------------------------------------------------------------------------------------
int psx_main(const int argc, const char* const* const argv) noexcept {
    // PsyDoom: setup logic for the new game host environment
    #if PSYDOOM_MODS
        // Parse command line arguments and configuration and initialize input systems
        Utils::installFatalErrorHandler();
        PSYDOOM_3DS_LOG("psx_main: installed the fatal error handler");

        ProgArgs::init(argc, argv);
        PSYDOOM_3DS_LOG("psx_main: parsed program arguments");

        if (!Controls::didInit()) {
            Controls::init();
        }

        PSYDOOM_3DS_LOG("psx_main: control bindings loaded");

        if (!Config::didInit()) {
            Config::init();
        }

        PSYDOOM_3DS_LOG("psx_main: configuration loaded");

        // PsyDoom 3DS: the audio buffer is not the player's to choose on fixed hardware, and a file written by an
        // earlier build would otherwise hold it at a value that breaks the sound up. Set after the config files have
        // been read, so that whatever they said is overruled.
        //
        // NDSP keeps two buffers, so the callback has one buffer's worth of time to fill the next: that has to be
        // longer than a frame takes, and 2048 samples is 46 ms against a frame of 33-42 ms.
        #if PSYDOOM_3DS
            Config::gAudioBufferSize = 2048;
        #endif

        Input::init();
        PSYDOOM_3DS_LOG("psx_main: input initialized");

        PlayerPrefs::load();
        PSYDOOM_3DS_LOG("psx_main: player preferences loaded");

        // Initialize the emulated PSX components using the PSX Doom disc (supplied as a .cue file).
        // This must be provided in order for the game to run.
        const char* const cueFilePath = (ProgArgs::gCueFileOverride) ? ProgArgs::gCueFileOverride : Config::gCueFilePath.c_str();

        if ((!cueFilePath) || (!cueFilePath[0])) {
            FatalErrors::raise(
                "The path to the .cue file for the game disc is not specified; PsyDoom needs this in order to run!\n"
                "\n"
                "You can set the path to the default .cue file by changing the 'CueFilePath' setting in 'game_cfg.ini'\n"
                "or via the 'Game' settings tab in the launcher.\n"
                "\n"
                "Alternatively, you can use the '-cue <CUE_FILE_PATH>' program argument to specify the .cue file."
            );
        }

        PSYDOOM_3DS_LOG("psx_main: initializing the emulated PlayStation with cue '%s'", cueFilePath);
        PSYDOOM_3DS_LOG("psx_main: %s", Platform3DS::memoryStatusString());

        if (!PsxVm::init(cueFilePath)) {
            PSYDOOM_3DS_LOG("psx_main: PsxVm::init FAILED - exiting");
            return 1;
        }

        PSYDOOM_3DS_LOG("psx_main: emulated PlayStation initialized");
        PSYDOOM_3DS_LOG("psx_main: %s", Platform3DS::memoryStatusString());

        // Determine the game type and variant and initialize the table of files on the CD from the file system
        Game::determineGameTypeAndVariant();
        PSYDOOM_3DS_LOG("psx_main: determined the game type and variant");

        CdMapTbl_Init();
        PSYDOOM_3DS_LOG("psx_main: built the CD file table");

        // Initialize the display, modding manager, cheats and intro logos
        Video::initVideo();
        PSYDOOM_3DS_LOG("psx_main: video initialized");

        ModMgr::init();
        Cheats::init();
        IntroLogos::init();
        PSYDOOM_3DS_LOG("psx_main: mods, cheats and intro logos initialized");
    #endif

    // Call the original PSX Doom 'main()' function
    PSYDOOM_3DS_LOG("psx_main: %s", Platform3DS::memoryStatusString());
    PSYDOOM_3DS_LOG("psx_main: entering I_Main");
    I_Main();
    PSYDOOM_3DS_LOG("psx_main: I_Main returned, shutting down");

    // PsyDoom: cleanup logic after Doom itself is done and save player prefs (unless headless mode)
    #if PSYDOOM_MODS
        const bool bIsCheckingADemoResult = (ProgArgs::gCheckDemoResultFilePath[0] != 0);

        if (!ProgArgs::gbHeadlessMode) {
            // PsyDoom 3DS: write the control bindings out as well as the preferences.
            //
            // 'Config::shutdown' below only clears the config structures; nothing writes them back. On desktop that is
            // fine, because the launcher is what edits them. There is no launcher here - bindings are changed in game -
            // and without this a scheme picked in the menu was remembered while the bindings it applied were not, so
            // the next launch read back the old bindings, found they disagreed with the saved scheme, and called the
            // layout 'Custom'. Which looked exactly like nothing having been saved at all.
            #if PSYDOOM_3DS
                PlayerPrefs::flushToDisk();
            #else
                PlayerPrefs::save();
            #endif
        }

        IntroLogos::shutdown();
        Video::shutdownVideo();
        PsxVm::shutdown();
        Cheats::shutdown();
        ModMgr::shutdown();
        Input::shutdown();
        Config::shutdown();
        Controls::shutdown();
        ProgArgs::shutdown();
        Utils::uninstallFatalErrorHandler();
    #endif

    // PsyDoom: if we were checking the result of a demo and it produced an unexpected outcome then return error code '1' to indicate that.
    // Otherwise return code '0' to indicate normal execution without any issues:
    #if PSYDOOM_MODS
        return (bIsCheckingADemoResult && gbCheckDemoResultFailed) ? 1 : 0;
    #else
        return 0;
    #endif
}
